export const animalCategories = {
  Domestic: {
    types: ["Dogs", "Cats", "Rabbits", "Hamsters"],
  },
  Poultry: {
    types: ["Hens", "Ducks"],
  },
  Livestock: {
    types: ["Sheep", "Goats"],
  },
  Wild: {
    types: ["Lion", "Tiger", "Bear"],
  },
};

export const animalBreeds = {
  Dogs: [
    "Labrador Retriever",
    "Golden Retriever",
    "German Shepherd",
    "Bulldog",
    "Beagle",
    "Poodle",
    "Rottweiler",
    "Boxer",
    "Dalmatian",
    "Chihuahua",
  ],
  Cats: [
    "Persian",
    "Siamese",
    "Maine Coon",
    "Bengal",
    "Ragdoll",
    "British Shorthair",
    "Abyssinian",
    "Sphynx",
    "Russian Blue",
    "Scottish Fold",
  ],
  Sheep: [
    "Merino",
    "Suffolk",
    "Dorper",
    "Dorset",
    "Cheviot",
    "Southdown",
    "Hampshire",
  ],
  Goats: ["Nubian", "Alpine", "Saanen", "Boer", "Toggenburg", "Pygmy", "Kiko"],
  Hens: [
    "Rhode Island Red",
    "Leghorn",
    "Sussex",
    "Plymouth Rock",
    "Orpington",
    "Wyandotte",
    "Australorp",
    "Silkie",
    "Marans",
  ],
  Rabbits: [
    "Holland Lop",
    "Mini Rex",
    "Dutch Rabbit",
    "Flemish Giant",
    "English Angora",
    "Lionhead Rabbit",
    "Mini Lop",
  ],
  Hamsters: [
    "Syrian",
    "Roborovski",
    "Dwarf Campbell’s",
    "Chinese",
    "Winter White",
    "European (Wild)",
  ],
  Ducks: [
    "Pekin",
    "Indian Runner",
    "Khaki Campbell",
    "Muscovy",
    "Mallard",
    "Rouen",
    "Cayuga",
  ],
};
